<a href="https://colab.research.google.com/github/HarshadNSuthar/Titanic_Survival_Keras/blob/master/Titanic_Survival_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
#Importing all required packages
import functools

import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
#importing Datasets

from google.colab import files

In [18]:
uploaded = files.upload()

Saving train.csv to train (1).csv


In [19]:
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

User uploaded file "train.csv" with length 30874 bytes


In [0]:
import io

In [0]:
# After Loading importing in pandas DataFrame
import pandas as pd

train = pd.read_csv(io.StringIO(uploaded['train.csv'].decode('utf-8')))

In [95]:
uploaded = files.upload()

Saving eval.csv to eval (3).csv


In [96]:
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

User uploaded file "eval.csv" with length 11643 bytes


In [0]:
# After Loading importing in pandas DataFrame
import pandas as pd

test = pd.read_csv(io.StringIO(uploaded['eval.csv'].decode('utf-8')))

In [105]:
LABEL_COLUMN = 'survived'
LABELS = [0, 1]

train.head()

survived  sex   age  n_siblings_spouses  ...  class  deck  embark_town  alone
0         0    1  22.0                   1  ...      2     7            2      0
1         1    0  38.0                   1  ...      0     2            0      0
2         1    0  26.0                   0  ...      2     7            2      1
3         1    0  35.0                   1  ...      0     2            2      0
4         0    1  28.0                   0  ...      2     7            1      1

[5 rows x 10 columns]

In [0]:
#Encoding Categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_x1 = LabelEncoder()
train['sex'] = labelencoder_x1.fit_transform(train['sex'])

labelencoder_x2 = LabelEncoder()
train['class'] = labelencoder_x1.fit_transform(train['class'])

labelencoder_x3 = LabelEncoder()
train['deck'] = labelencoder_x1.fit_transform(train['deck'])


labelencoder_x4 = LabelEncoder()
train['embark_town'] = labelencoder_x1.fit_transform(train['embark_town'])

labelencoder_x5 = LabelEncoder()
train['alone'] = labelencoder_x1.fit_transform(train['alone'])


In [0]:
# One Hot encoding
import numpy as np
from keras.utils import to_categorical

one_hot_encode = to_categorical(train['survived'])

In [110]:
one_hot_encode

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [0]:
x = train.iloc[:, 1:9].values
y = train.iloc[:, 0].values

In [0]:
#splitting the data into train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [0]:
# Feature Scalling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [0]:
# importing keras library and packages 
import keras
from keras.models import Sequential
from keras.layers import Dense

In [0]:
#Initializing the ANN

In [116]:
classifier = Sequential()
classifier.add(Dense(output_dim = 5, init = 'uniform', activation = 'relu', input_dim = 8)) 
# adding the input layer and the Second hidden layer
classifier.add(Dense(output_dim = 5, init = 'uniform', activation = 'relu'))
# adding the output layer 
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))  
# Compiling the ANN
classifier.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics = ['accuracy'] )


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=8, units=5, kernel_initializer="uniform")`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=5, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [117]:
# Fitting the ANN to the trainig set

classifier.fit(x_train, y_train, batch_size= 10, epochs = 100)

Epoch 1/100
501/501 [==============================] - 0s 322us/step - loss: 0.6910 - accuracy: 0.6208
Epoch 2/100
501/501 [==============================] - 0s 99us/step - loss: 0.6833 - accuracy: 0.6267
Epoch 3/100
501/501 [==============================] - 0s 99us/step - loss: 0.6626 - accuracy: 0.6267
Epoch 4/100
501/501 [==============================] - 0s 102us/step - loss: 0.6218 - accuracy: 0.6267
Epoch 5/100
501/501 [==============================] - 0s 102us/step - loss: 0.5787 - accuracy: 0.6267
Epoch 6/100
501/501 [==============================] - 0s 103us/step - loss: 0.5525 - accuracy: 0.6267
Epoch 7/100
501/501 [==============================] - 0s 103us/step - loss: 0.5362 - accuracy: 0.6267
Epoch 8/100
501/501 [==============================] - 0s 103us/step - loss: 0.5254 - accuracy: 0.6267
Epoch 9/100
501/501 [==============================] - 0s 103us/step - loss: 0.5189 - accuracy: 0.6267
Epoch 10/100
501/501 [==============================] - 0s 113us/step - los

In [0]:
# predicting the test and result

y_pred = classifier.predict(x_test)

# here we have predicted the probability we need to convert to 0 or 1

y_pred = (y_pred > 0.5)

In [119]:
# Making the confusion Matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

cm

array([[65,  5],
       [12, 44]])

In [120]:
#accuracy = no.of correct pred/total no.of pred

(65 + 44)/126

0.8650793650793651

In [121]:
"""predicting single new customer with folowing information
sex : 1
age : 35
n_siblings_spouses : 0
parch : 0
fare : 8.05
class : 2
deck : 7
embark_town : 2
alone : 0   """

'predicting single new customer with folowing information\nsex : 1\nage : 35\nn_siblings_spouses : 0\nparch : 0\nfare : 8.05\nclass : 2\ndeck : 7\nembark_town : 2\nalone : 0   '

In [0]:
New_prediction = classifier.predict(sc.transform(np.array([[0, 58, 0, 0, 26.55, 0, 4, 2]])))

In [126]:
New_prediction

array([[0.921905]], dtype=float32)

In [0]:
New_prediction =(New_prediction > 0.5)

In [128]:
New_prediction

array([[ True]])